logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    cn.itcast: debug
spring:
  rabbitmq:
    #    host: 192.168.21.129 # rabbitMQ的ip地址
    #    port: 5672 # 端口
    username: root
    password: root
    virtual-host: /
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 3
          max-attempts: 4
    addresses: 192.168.21.129:8071,192.168.21.129:8072,192.168.21.129:8073
