server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/heima?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    username: root
    password: root
    host: 192.168.21.129
    port: 5672
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo